
export const gameData = {
  debutant: {
    vocab: [
      { question: "Que signifie 'rosa' ?", options: ["rose", "rouge", "rivière", "reine"], correct: 0 },
      { question: "Que signifie 'aqua' ?", options: ["air", "feu", "eau", "terre"], correct: 2 },
      { question: "Que signifie 'puella' ?", options: ["garçon", "fille", "homme", "femme"], correct: 1 },
      { question: "Que signifie 'liber' ?", options: ["liberté", "livre", "libre", "lierre"], correct: 1 },
      { question: "Que signifie 'mater' ?", options: ["père", "mère", "frère", "sœur"], correct: 1 },
      { question: "Que signifie 'pater' ?", options: ["père", "mère", "pain", "paix"], correct: 0 },
      { question: "Que signifie 'domus' ?", options: ["dôme", "maison", "domaine", "dormir"], correct: 1 },
      { question: "Que signifie 'via' ?", options: ["vie", "voie/route", "voir", "ville"], correct: 1 },
      { question: "Que signifie 'terra' ?", options: ["terreur", "terre", "terrasse", "territoire"], correct: 1 },
      { question: "Que signifie 'sol' ?", options: ["soleil", "sol", "soldat", "seul"], correct: 0 },
      { question: "Que signifie 'luna' ?", options: ["lundi", "lune", "lumière", "lunettes"], correct: 1 },
      { question: "Que signifie 'stella' ?", options: ["style", "étoile", "statue", "stable"], correct: 1 },
      { question: "Que signifie 'rex' ?", options: ["règle", "roi", "reine", "rectangle"], correct: 1 },
      { question: "Que signifie 'regina' ?", options: ["règle", "région", "reine", "regret"], correct: 2 },
      { question: "Que signifie 'filius' ?", options: ["fille", "fils", "fil", "filtre"], correct: 1 },
      { question: "Que signifie 'filia' ?", options: ["fille", "fils", "file", "filiale"], correct: 0 },
      { question: "Que signifie 'puer' ?", options: ["garçon", "fille", "pur", "peur"], correct: 0 },
      { question: "Que signifie 'amicus' ?", options: ["amour", "ami", "âme", "amidon"], correct: 1 },
      { question: "Que signifie 'amica' ?", options: ["amie", "ami", "amour", "amiral"], correct: 0 },
      { question: "Que signifie 'poeta' ?", options: ["poète", "poème", "poésie", "poétique"], correct: 0 },
    ],
    conjugaison: [
      { question: "Conjuguez 'amare' à la 1ère personne du singulier (présent)", options: ["amo", "amas", "amat", "amamus"], correct: 0, temps: "present", voix: "actif" },
      { question: "Conjuguez 'esse' à la 3ème personne du singulier (présent)", options: ["sum", "es", "est", "sumus"], correct: 2, temps: "present", voix: "actif" },
      { question: "La forme passive de 'amo' est :", options: ["amans", "amor", "amatus", "amare"], correct: 1, temps: "present", voix: "passif" },
      { question: "Conjuguez 'habere' à la 1ère personne du pluriel (présent)", options: ["habeo", "habes", "habet", "habemus"], correct: 3, temps: "present", voix: "actif" },
      { question: "Conjuguez 'venire' à la 2ème personne du singulier (présent)", options: ["venio", "venis", "venit", "venimus"], correct: 1, temps: "present", voix: "actif" },
      { question: "Conjuguez 'laudare' à la 3ème personne du pluriel (présent)", options: ["laudo", "laudas", "laudat", "laudant"], correct: 3, temps: "present", voix: "actif" },
      { question: "'amabam' est à l'imparfait. A quelle personne ?", options: ["1ère sing.", "2ème sing.", "3ème sing.", "1ère plur."], correct: 0, temps: "imparfait", voix: "actif" },
      { question: "'laudabatis' est à l'imparfait. A quelle personne ?", options: ["1ère plur.", "2ème plur.", "3ème plur.", "2ème sing."], correct: 1, temps: "imparfait", voix: "actif" },
      { question: "'amavi' est au parfait. A quelle personne ?", options: ["1ère sing.", "2ème sing.", "3ème sing.", "1ère plur."], correct: 0, temps: "parfait", voix: "actif" },
      { question: "'fuerunt' est la 3ème personne du pluriel du parfait de quel verbe ?", options: ["facere", "ferre", "esse", "velle"], correct: 2, temps: "parfait", voix: "actif" },
      { question: "'amabitur' est au futur passif. A quelle personne ?", options: ["1ère sing.", "2ème sing.", "3ème sing.", "3ème plur."], correct: 2, temps: "futur", voix: "passif" },
    ],
    temps: [
        { question: "Quel temps est 'amavi' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 2, temps: "parfait" },
        { question: "Quel temps est 'amabam' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 1, temps: "imparfait" },
        { question: "Quel temps est 'amo' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 0, temps: "present" },
        { question: "Quel temps est 'amabo' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 3, temps: "futur" },
        { question: "Quel temps est 'amaveram' ?", options: ["imparfait", "parfait", "plus-que-parfait", "futur"], correct: 2, temps: "plusqueparfait" },
        { question: "Quel temps est 'laudat' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 0, temps: "present" },
        { question: "Quel temps est 'laudabat' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 1, temps: "imparfait" },
        { question: "Quel temps est 'laudavit' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 2, temps: "parfait" },
        { question: "Quel temps est 'laudabit' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 3, temps: "futur" },
        { question: "Quel temps est 'habui' ?", options: ["présent", "imparfait", "parfait", "futur"], correct: 2, temps: "parfait" },
    ],
    culture: [
      { question: "Qui était le premier empereur romain ?", options: ["Jules César", "Auguste", "Néron", "Tibère"], correct: 1 },
      { question: "Quelle ville a été détruite par le Vésuve en 79 ap. J.-C. ?", options: ["Rome", "Pompéi", "Athènes", "Carthage"], correct: 1 },
      { question: "Quel animal symbolisait Rome ?", options: ["Aigle", "Lion", "Louve", "Cheval"], correct: 2 },
      { question: "Qui a fondé Rome selon la légende ?", options: ["Rémus", "Romulus", "Énée", "Mars"], correct: 1 },
      { question: "Quel était le nom du grand cirque romain ?", options: ["Circus Maximus", "Colisée", "Forum", "Panthéon"], correct: 0 },
      { question: "Qui était le dieu romain de la guerre ?", options: ["Jupiter", "Mars", "Neptune", "Apollon"], correct: 1 },
      { question: "Comment s'appelait le roi des dieux ?", options: ["Zeus", "Jupiter", "Mars", "Saturne"], correct: 1 },
      { question: "Comment s'appelaient les routes romaines ?", options: ["Viae", "Strada", "Chemins", "Autoroutes"], correct: 0 },
      { question: "Quel était le vêtement traditionnel des citoyens romains ?", options: ["Tunique", "Robe", "Toge", "Pantalon"], correct: 2 },
      { question: "Qui était la déesse de l'amour ?", options: ["Junon", "Minerve", "Vénus", "Diane"], correct: 2 },
    ],
    citations: [
      { question: "Qui a dit 'Veni, vidi, vici' ?", options: ["Cicéron", "Jules César", "Auguste", "Virgile"], correct: 1 },
      { question: "Que signifie 'Carpe diem' ?", options: ["Profite du jour", "La vie est belle", "Le temps passe", "Sois heureux"], correct: 0 },
      { question: "Que signifie 'Alea iacta est' ?", options: ["Le sort en est jeté", "Les dés sont pipés", "La partie est finie", "J'ai gagné"], correct: 0 },
      { question: "Que signifie 'Errare humanum est' ?", options: ["L'erreur est humaine", "Les humains sont mauvais", "Il faut errer", "L'errance est une vertu"], correct: 0 },
      { question: "Que signifie 'Tempus fugit' ?", options: ["Le temps s'enfuit", "Le temps est glacial", "Il fait beau", "Le temps change"], correct: 0 },
    ],
    phrases: [
      { question: "Puella rosam amat", options: ["La fille aime la rose", "La rose aime la fille", "Les filles aiment les roses", "La fille a une rose"], correct: 0 },
      { question: "Aqua est bona", options: ["L'eau est mauvaise", "L'eau est bonne", "L'eau est chaude", "L'eau est froide"], correct: 1 },
      { question: "Pater in casa est", options: ["Le père est dans la maison", "Le père va à la maison", "Le père sort de la maison", "Le père aime la maison"], correct: 0 },
      { question: "Poeta scribit", options: ["Le poète écrit", "Le poète lit", "Le poète chante", "Le poète dort"], correct: 0 },
      { question: "Nauta navigat", options: ["Le marin navigue", "Le marin pêche", "Le marin nage", "Le marin se repose"], correct: 0 },
    ],
    reconstitution: [
      { french: "La fille aime la rose", words: ["Puella", "rosam", "amat"], correct: ["Puella", "rosam", "amat"], declinaisons: ["nominatif", "accusatif"] },
      { french: "L'eau est bonne", words: ["Aqua", "est", "bona"], correct: ["Aqua", "est", "bona"], declinaisons: ["nominatif"] },
      { french: "Le poète écrit un livre", words: ["Poeta", "librum", "scribit"], correct: ["Poeta", "librum", "scribit"], declinaisons: ["nominatif", "accusatif"] },
      { french: "Le soldat est courageux", words: ["Miles", "fortis", "est"], correct: ["Miles", "fortis", "est"], declinaisons: ["nominatif"] },
      { french: "La mère aime son fils", words: ["Mater", "filium", "amat"], correct: ["Mater", "filium", "amat"], declinaisons: ["nominatif", "accusatif"] },
    ],
    vraifaux: [
      { latin: "Rosa", french: "Rose", correct: true },
      { latin: "Aqua", french: "Feu", correct: false },
      { latin: "Puella", french: "Fille", correct: true },
      { latin: "Liber", french: "Liberté", correct: false },
      { latin: "Mater", french: "Mère", correct: true },
      { latin: "Pater", french: "Frère", correct: false },
      { latin: "Domus", french: "Maison", correct: true },
      { latin: "Via", french: "Vie", correct: false },
      { latin: "Terra", french: "Terre", correct: true },
      { latin: "Sol", french: "Lune", correct: false },
    ],
    declinaison: [
        { question: "Quelle est la terminaison du génitif singulier de la 1ère déclinaison ?", options: ["-a", "-ae", "-am", "-arum"], correct: 1, declinaison: "1ere" },
        { question: "Le mot 'rosa' (la rose) est à la 1ère déclinaison. Quel est son accusatif pluriel ?", options: ["rosas", "rosae", "rosis", "rosarum"], correct: 0, declinaison: "1ere" },
        { question: "Quelle est la terminaison du nominatif singulier pour les noms masculins de la 2ème déclinaison en -us ?", options: ["-us", "-um", "-i", "-o"], correct: 0, declinaison: "2eme" },
        { question: "Le mot 'dominus' (le maître) est à la 2ème déclinaison. Quel est son datif singulier ?", options: ["domine", "dominum", "domino", "domini"], correct: 2, declinaison: "2eme" },
        { question: "La 3ème déclinaison a des modèles... ?", options: ["Uniquement masculins", "Uniquement féminins", "Masculins, féminins et neutres", "Uniquement neutres"], correct: 2, declinaison: "3eme" },
        { question: "Le mot 'rex' (le roi) est de la 3ème déclinaison. Quel est son génitif singulier ?", options: ["rex", "regis", "regi", "regem"], correct: 1, declinaison: "3eme" },
        { question: "Quelle est la terminaison du nominatif singulier de la 4ème déclinaison (masculin) ?", options: ["-us", "-u", "-um", "-ibus"], correct: 0, declinaison: "4eme" },
        { question: "Le mot 'manus' (la main) est à la 4ème déclinaison. Quel est son ablatif pluriel ?", options: ["manus", "manuum", "manibus", "manum"], correct: 2, declinaison: "4eme" },
        { question: "Quelle est la terminaison du génitif singulier de la 5ème déclinaison ?", options: ["-es", "-ei", "-em", "-e"], correct: 1, declinaison: "5eme" },
        { question: "Le mot 'res' (la chose) est à la 5ème déclinaison. Quel est son accusatif pluriel ?", options: ["res", "rerum", "rebus", "res"], correct: 0, declinaison: "5eme" }
    ]
  },
  intermediaire: {
    vocab: [
      { question: "Que signifie 'fortis' ?", options: ["faible", "fort/courageux", "rapide", "lent"], correct: 1 },
      { question: "Que signifie 'bellum' ?", options: ["beauté", "guerre", "paix", "belle"], correct: 1 },
      { question: "Que signifie 'civis' ?", options: ["civil", "citoyen", "campagne", "ville"], correct: 1 },
      { question: "Que signifie 'lex' ?", options: ["lire", "loi", "lit", "légume"], correct: 1 },
      { question: "Que signifie 'tempus' ?", options: ["tempête", "temps", "temple", "temporaire"], correct: 1 },
      { question: "Que signifie 'hostis' ?", options: ["hôte", "hospitalier", "ennemi", "otage"], correct: 2 },
      { question: "Que signifie 'dux' ?", options: ["duc", "doux", "deux", "chef/général"], correct: 3 },
      { question: "Que signifie 'pax' ?", options: ["pas", "pain", "paix", "pacte"], correct: 2 },
      { question: "Que signifie 'lux' ?", options: ["luxe", "lumière", "lustre", "lunettes"], correct: 1 },
      { question: "Que signifie 'mors' ?", options: ["mordu", "morse", "mort", "morceau"], correct: 2 },
    ],
    conjugaison: [
        { question: "Conjuguez 'capere' à la 3ème personne du pluriel (présent)", options: ["capio", "capis", "capit", "capiunt"], correct: 3, temps: "present", voix: "actif" },
        { question: "'amatur' est la forme passive au présent de 'amare'. A quelle personne ?", options: ["1ère sing.", "2ème sing.", "3ème sing.", "1ère plur."], correct: 2, temps: "present", voix: "passif" },
        { question: "Conjuguez 'dicere' au parfait, 1ère personne du singulier", options: ["dico", "dicebam", "dixi", "dicam"], correct: 2, temps: "parfait", voix: "actif" },
        { question: "Le plus-que-parfait de 'esse' à la 3ème pers. sing. est :", options: ["erat", "fuit", "fuerat", "erit"], correct: 2, temps: "plusqueparfait", voix: "actif" },
        { question: "Conjuguez 'audire' au futur, 2ème pers. sing.", options: ["audis", "audiebas", "audies", "audivisti"], correct: 2, temps: "futur", voix: "actif" },
        { question: "La forme passive de 'capit' (il/elle prend) est :", options: ["captur", "capitur", "capiatur", "captus est"], correct: 1, temps: "present", voix: "passif" },
        { question: "Conjuguez 'amare' à l'imparfait passif, 3ème pers. sing.", options: ["amatur", "amabatur", "amatus est", "amaretur"], correct: 1, temps: "imparfait", voix: "passif" },
        { question: "Le participe parfait passif de 'mittere' (envoyer) est :", options: ["mittens", "missus", "misit", "mittetur"], correct: 1, temps: "parfait", voix: "passif" },
        { question: "'moniti sunt' est le parfait passif de 'monere'. A quelle personne ?", options: ["1ère plur.", "2ème plur.", "3ème plur.", "3ème sing."], correct: 2, temps: "parfait", voix: "passif" },
        { question: "Conjuguez 'regere' (diriger) au futur actif, 1ère pers. plur.", options: ["regimus", "regemus", "rexerimus", "regemur"], correct: 1, temps: "futur", voix: "actif" },
    ],
    temps: [
        { question: "Quel temps est 'amaveram' ?", options: ["imparfait", "parfait", "plus-que-parfait", "futur antérieur"], correct: 2, temps: "plusqueparfait" },
        { question: "Quel temps est 'amatus sum' ?", options: ["présent passif", "parfait passif", "futur passif", "imparfait passif"], correct: 1, temps: "parfait" },
        { question: "'dixerat' est à quel temps de l'indicatif ?", options: ["imparfait", "parfait", "futur antérieur", "plus-que-parfait"], correct: 3, temps: "plusqueparfait" },
        { question: "'audietur' est à quel temps ?", options: ["présent passif", "futur passif", "parfait passif", "imparfait passif"], correct: 1, temps: "futur" },
        { question: "'capiebam' est à quel temps ?", options: ["présent", "imparfait", "futur", "parfait"], correct: 1, temps: "imparfait" },
        { question: "'rexerunt' est à quel temps ?", options: ["présent", "imparfait", "parfait", "plus-que-parfait"], correct: 2, temps: "parfait" },
        { question: "'moniti erimus' est à quel temps ?", options: ["parfait passif", "futur antérieur passif", "futur passif", "plus-que-parfait passif"], correct: 1, temps: "futur" },
    ],
    culture: [
        { question: "Combien de collines comptait Rome ?", options: ["5", "7", "9", "12"], correct: 1 },
        { question: "Qui a écrit l'Énéide ?", options: ["Homère", "Ovide", "Virgile", "Horace"], correct: 2 },
        { question: "Quelle bataille navale a vu la victoire d'Octave sur Antoine et Cléopâtre ?", options: ["Salamine", "Actium", "Lépante", "Zama"], correct: 1 },
        { question: "Quel était le nom de la place publique principale à Rome ?", options: ["Agora", "Acropole", "Forum Romanum", "Circus Maximus"], correct: 2 },
        { question: "Quel empereur a lancé la construction du Colisée ?", options: ["Néron", "Auguste", "Vespasien", "Trajan"], correct: 2 },
        { question: "Qui était le rival de Jules César dans la guerre civile ?", options: ["Crassus", "Pompée", "Catilina", "Brutus"], correct: 1 },
        { question: "Quel est le nom du poète comique auteur de 'L'Aulularia' (La Marmite) ?", options: ["Térence", "Plaute", "Sénèque", "Ovide"], correct: 1 },
        { question: "Quel empereur était aussi connu comme un philosophe stoïcien ?", options: ["Caligula", "Néron", "Commode", "Marc Aurèle"], correct: 3 },
    ],
    citations: [
        { question: "Que signifie 'Alea iacta est' ?", options: ["Les dés sont jetés", "Le sort en est jeté", "C'est joué", "Toutes ces réponses sont acceptables"], correct: 3 },
        { question: "Que signifie 'Memento mori' ?", options: ["Souviens-toi de vivre", "Souviens-toi que tu vas mourir", "N'oublie pas la mort", "La mort est un souvenir"], correct: 1 },
        { question: "Que signifie 'Si vis pacem, para bellum' ?", options: ["Si tu veux la paix, prépare la guerre", "La paix s'obtient par la guerre", "Vise la paix, prépare-toi au combat", "La paix est une guerre préparée"], correct: 0 },
        { question: "Qui a écrit 'De Bello Gallico' (La Guerre des Gaules) ?", options: ["Tacite", "Suétone", "Jules César", "Tite-Live"], correct: 2 },
        { question: "Que signifie 'Panem et circenses' ?", options: ["Du pain et de l'eau", "La nourriture et la boisson", "Du pain et des jeux du cirque", "Le pain est un jeu"], correct: 2 },
        { question: "Que signifie 'Audaces fortuna iuvat' ?", options: ["La fortune aide les audacieux", "La chance n'aide personne", "L'audace est une fortune", "La fortune est audacieuse"], correct: 0 },
    ],
    phrases: [
        { question: "Miles fortis in bello pugnat", options: ["Le soldat fort combat dans la guerre", "Le soldat faible fuit la guerre", "Les soldats forts gagnent", "Le soldat revient de guerre"], correct: 0 },
        { question: "Urbs magna est Roma", options: ["Rome est une petite ville", "Rome est une grande ville", "Rome était une ville", "Rome sera une ville"], correct: 1 },
        { question: "Dux exercitum ad victoriam duxit.", options: ["Le chef a mené l'armée à la victoire", "L'armée a conduit le chef à la victoire", "Le chef mène l'armée à la victoire", "L'armée est victorieuse sans chef"], correct: 0 },
        { question: "Cives leges bonas laudant.", options: ["Les citoyens louent les bonnes lois", "Les bonnes lois louent les citoyens", "Les citoyens veulent de bonnes lois", "Les citoyens n'aiment pas les lois"], correct: 0 },
        { question: "Hostes ab urbe pulsi sunt.", options: ["Les ennemis ont attaqué la ville", "La ville a repoussé les ennemis", "Les ennemis ont été chassés de la ville", "Les ennemis sont dans la ville"], correct: 2 },
    ],
    reconstitution: [
        { french: "Le soldat courageux combat", words: ["Miles", "fortis", "pugnat"], correct: ["Miles", "fortis", "pugnat"], declinaisons: ["nominatif"] },
        { french: "La loi est juste", words: ["Lex", "iusta", "est"], correct: ["Lex", "est", "iusta"], declinaisons: ["nominatif"] },
        { french: "Le chef mène l'armée", words: ["Dux", "exercitum", "ducit"], correct: ["Dux", "exercitum", "ducit"], declinaisons: ["nominatif", "accusatif"] },
        { french: "J'ai donné un livre au citoyen", words: ["Civi", "librum", "dedi"], correct: ["Librum", "civi", "dedi"], declinaisons: ["datif", "accusatif"] },
        { french: "La lumière du soleil est grande", words: ["Lux", "solis", "magna", "est"], correct: ["Lux", "solis", "magna", "est"], declinaisons: ["nominatif", "genitif"] },
        { french: "Ils ont combattu avec courage", words: ["Cum", "virtute", "pugnaverunt"], correct: ["Cum", "virtute", "pugnaverunt"], declinaisons: ["ablatif"] },
    ],
    vraifaux: [
        { latin: "Fortis", french: "Fort", correct: true },
        { latin: "Bellum", french: "Beauté", correct: false },
        { latin: "Civis", french: "Ville", correct: false },
        { latin: "Lex", french: "Loi", correct: true },
        { latin: "Tempus", french: "Temps", correct: true },
        { latin: "Hostis", french: "Ennemi", correct: true },
        { latin: "Dux", french: "Deux", correct: false },
        { latin: "Mors", french: "Mort", correct: true },
    ],
    declinaison: [
        { question: "Quelle est la terminaison du génitif singulier de la 1ère déclinaison ?", options: ["-a", "-ae", "-am", "-arum"], correct: 1, declinaison: "1ere" },
        { question: "Le mot 'poeta' (poète, masc.) est à la 1ère déclinaison. Quel est son datif pluriel ?", options: ["poetis", "poetas", "poetarum", "poetae"], correct: 0, declinaison: "1ere" },
        { question: "Quelle est la terminaison du nominatif singulier pour les noms neutres de la 2ème déclinaison ?", options: ["-us", "-um", "-i", "-o"], correct: 1, declinaison: "2eme" },
        { question: "'agri' est le génitif singulier de 'ager' (le champ). Quel est son accusatif singulier ?", options: ["agrum", "agro", "ager", "agri"], correct: 0, declinaison: "2eme" },
        { question: "La 3ème déclinaison a des modèles... ?", options: ["Uniquement parisyllabiques", "Uniquement imparisyllabiques", "Parisyllabiques et imparisyllabiques", "Uniquement neutres"], correct: 2, declinaison: "3eme" },
        { question: "Le mot 'civis' (le citoyen) est de la 3ème déclinaison. Quel est son génitif pluriel ?", options: ["civis", "civium", "cives", "civibus"], correct: 1, declinaison: "3eme" },
        { question: "Quelle est la terminaison du génitif singulier de la 4ème déclinaison ?", options: ["-us", "-u", "-ui", "-um"], correct: 0, declinaison: "4eme" },
        { question: "Le mot 'cornu' (la corne, neutre) est à la 4ème déclinaison. Quel est son accusatif pluriel ?", options: ["cornus", "cornua", "cornibus", "cornuum"], correct: 1, declinaison: "4eme" },
        { question: "Quelle est la terminaison du génitif pluriel de la 5ème déclinaison ?", options: ["-es", "-ei", "-erum", "-ebus"], correct: 2, declinaison: "5eme" },
        { question: "Le mot 'dies' (le jour) est à la 5ème déclinaison. Quel est son ablatif singulier ?", options: ["dies", "diei", "diem", "die"], correct: 3, declinaison: "5eme" }
    ]
  },
  avance: {
    vocab: [
      { question: "Que signifie 'virtus' ?", options: ["vertu/courage", "vice", "vérité", "victoire"], correct: 0 },
      { question: "Que signifie 'sapientia' ?", options: ["science", "sagesse", "saveur", "salut"], correct: 1 },
      { question: "Que signifie 'res publica' ?", options: ["la chose publique/l'État", "la richesse publique", "la réponse publique", "la rébellion publique"], correct: 0 },
      { question: "Que signifie 'otium' ?", options: ["huit", "loisir/paix", "haine", "oreille"], correct: 1 },
      { question: "Que signifie 'negotium' ?", options: ["négation", "commerce/affaire", "négociation", "négligence"], correct: 1 },
      { question: "Que signifie 'foedus' ?", options: ["fédéral", "foi", "traité/pacte", "laid"], correct: 2 },
      { question: "Que signifie 'coniuratio' ?", options: ["conjugaison", "conjuration/complot", "blessure", "jugement"], correct: 1 },
      { question: "Que signifie 'eloquentia' ?", options: ["élégance", "éloquence", "élévation", "élection"], correct: 1 },
      { question: "Que signifie 'auctoritas' ?", options: ["autorité/prestige", "auteur", "augmentation", "automne"], correct: 0 },
      { question: "Que signifie 'mos maiorum' ?", options: ["la mort des ancêtres", "les mœurs des anciens", "le mur des lamentations", "le mois de mai"], correct: 1 },
    ],
    conjugaison: [
        { question: "Conjuguez 'ferre' (porter) au subjonctif présent, 1ère pers. sing.", options: ["fero", "feram", "tulerim", "ferrem"], correct: 1, temps: "present", voix: "actif" },
        { question: "Quel est le participe parfait passif de 'frangere' (briser) ?", options: ["frangens", "fractus", "fregi", "frangendus"], correct: 1, temps: "parfait", voix: "passif" },
        { question: "Le subjonctif imparfait de 'esse', 3ème pers. plur. est :", options: ["sint", "essent", "fuerint", "erant"], correct: 1, temps: "imparfait", voix: "actif" },
        { question: "Le gérondif au génitif de 'sequi' (suivre, déponent) est :", options: ["sequens", "sequendi", "secutus", "sequendum"], correct: 1, temps: "present", voix: "passif" },
        { question: "Quel est l'infinitif parfait actif de 'videre' ?", options: ["videre", "visus esse", "vidisse", "visurum esse"], correct: 2, temps: "parfait", voix: "actif" },
        { question: "Conjuguez 'audire' au subjonctif parfait passif, 1ère pers. sing.", options: ["auditus sim", "audiar", "audirer", "audivissem"], correct: 0, temps: "parfait", voix: "passif" },
        { question: "Le participe futur actif de 'mori' (mourir, déponent) est :", options: ["moriens", "moriturus", "mortuus", "moriendus"], correct: 1, temps: "futur", voix: "passif" },
        { question: "Conjuguez 'velle' (vouloir) au présent du subjonctif, 1ère pers. plur.", options: ["volumus", "velimus", "volemus", "voluerimus"], correct: 1, temps: "present", voix: "actif" },
        { question: "Le subjonctif plus-que-parfait de 'facere', 3ème pers. sing. est :", options: ["faciat", "fecerit", "fecisset", "faceret"], correct: 2, temps: "plusqueparfait", voix: "actif" },
        { question: "L'impératif futur de 'scire' (savoir), 2ème pers. sing. est :", options: ["sci", "scito", "scias", "scies"], correct: 1, temps: "futur", voix: "actif" },
    ],
    temps: [
        { question: "Dans 'cum vidissem', quel est le temps et le mode ?", options: ["indicatif plus-que-parfait", "subjonctif imparfait", "subjonctif parfait", "subjonctif plus-que-parfait"], correct: 3, temps: "plusqueparfait" },
        { question: "Quel temps est 'amavero' ?", options: ["futur simple", "futur antérieur", "parfait du subjonctif", "plus-que-parfait"], correct: 1, temps: "futur" },
        { question: "Quel temps est 'amatus ero' ?", options: ["parfait passif", "futur passif", "futur antérieur passif", "plus-que-parfait passif"], correct: 2, temps: "futur" },
        { question: "'feratur' est un subjonctif présent passif. Vrai ou Faux ?", options: ["Vrai", "Faux"], correct: 0, temps: "present" },
        { question: "'loquerer' est un subjonctif imparfait (verbe déponent). Vrai ou Faux ?", options: ["Vrai", "Faux"], correct: 0, temps: "imparfait" },
        { question: "'secuti sint' est un subjonctif parfait (verbe déponent). Vrai ou Faux ?", options: ["Vrai", "Faux"], correct: 0, temps: "parfait" },
        { question: "Quel est le temps de 'tulerit' ?", options: ["parfait de l'indicatif", "futur antérieur", "parfait du subjonctif", "les deux derniers sont possibles"], correct: 3, temps: "parfait" },
    ],
    culture: [
        { question: "Qui était le dernier roi de Rome ?", options: ["Romulus", "Numa Pompilius", "Tarquin le Superbe", "Servius Tullius"], correct: 2 },
        { question: "Quel général carthaginois a traversé les Alpes avec des éléphants ?", options: ["Hannibal Barca", "Hamilcar Barca", "Hasdrubal Barca", "Scipion l'Africain"], correct: 0 },
        { question: "Que signifie l'acronyme SPQR ?", options: ["Senatus Populusque Romanus", "Salus Populi Romani Suprema", "Senatus Populus Quirites Romani", "Servus Populi Romani"], correct: 0 },
        { question: "Qui a réformé le calendrier en 45 av. J.-C. ?", options: ["Auguste", "Jules César", "Pompée", "Numa Pompilius"], correct: 1 },
        { question: "Quel philosophe romain, précepteur de Néron, a écrit 'De la brièveté de la vie' ?", options: ["Cicéron", "Sénèque", "Marc Aurèle", "Épictète"], correct: 1 },
        { question: "Qui a écrit les 'Métamorphoses', une source majeure pour la mythologie gréco-romaine ?", options: ["Virgile", "Horace", "Ovide", "Catulle"], correct: 2 },
        { question: "Quel empereur a fait construire un célèbre mur en Bretagne (actuelle Grande-Bretagne) ?", options: ["Trajan", "Hadrien", "Antonin le Pieux", "Marc Aurèle"], correct: 1 },
        { question: "Quelle charge politique était la plus haute durant la République romaine ?", options: ["Sénateur", "Consul", "Préteur", "Tribun de la plèbe"], correct: 1 },
        { question: "Qui a écrit une histoire de Rome ('Ab Urbe Condita Libri') depuis sa fondation ?", options: ["Tacite", "Suétone", "Salluste", "Tite-Live"], correct: 3 },
        { question: "Quel poète a écrit les 'Odes' et les 'Satires' sous le règne d'Auguste ?", options: ["Virgile", "Properce", "Tibulle", "Horace"], correct: 3 },
    ],
    citations: [
        { question: "Que signifie 'Cogito ergo sum' ?", options: ["Je pense donc je suis (Descartes)", "Je doute donc j'existe", "Je réfléchis donc je vis", "Je sais donc je suis"], correct: 0 },
        { question: "Qui a dit 'Homo homini lupus' ?", options: ["Plaute", "Cicéron", "Hobbes (citant Plaute)", "Sénèque"], correct: 0 },
        { question: "Que signifie 'O tempora, o mores !' (Cicéron) ?", options: ["Ô temps, ô mœurs !", "Les temps sont durs", "Les mœurs se perdent", "Le bon vieux temps"], correct: 0 },
        { question: "Que signifie 'Dulce et decorum est pro patria mori' (Horace) ?", options: ["Il est doux et honorable de mourir pour la patrie", "Mourir pour la patrie est une décoration", "La patrie est douce et belle", "La mort est douce pour la patrie"], correct: 0 },
        { question: "'Quis custodiet ipsos custodes?' (Juvénal) se traduit par :", options: ["Qui garde les côtes ?", "Qui gardera les gardiens eux-mêmes ?", "Où sont les gardes ?", "Les gardes se surveillent"], correct: 1 },
        { question: "Que signifie 'Nunc est bibendum' (Horace) ?", options: ["Maintenant, il faut boire", "Il ne faut jamais boire", "Bois avec modération", "Buvons à notre victoire"], correct: 0 },
        { question: "Que signifie 'Oderint dum metuant' (Accius, repris par Caligula) ?", options: ["Qu'ils me détestent, pourvu qu'ils me craignent", "Ils détestent ceux qu'ils craignent", "La haine engendre la peur", "Je préfère la peur à la haine"], correct: 0 },
    ],
    phrases: [
        { question: "Veni, vidi, vici", options: ["Je suis venu, j'ai vu, j'ai vaincu", "Viens, vois, vaincs", "Il vint, il vit, il vainquit", "Nous venons, voyons, vainquons"], correct: 0 },
        { question: "Philosophia est ancilla theologiae.", options: ["La philosophie est la servante de la théologie", "La philosophie aide la théologie", "La philosophie est l'ennemie de la théologie", "La théologie sert la philosophie"], correct: 0 },
        { question: "Quidquid latine dictum sit, altum videtur.", options: ["Tout ce qui est dit en latin paraît profond", "Le latin est une langue profonde", "Il faut parler latin pour être profond", "Le latin est difficile"], correct: 0 },
        { question: "Caesar, pontem in Rheno facere instituit.", options: ["César décide de construire un pont sur le Rhin", "Le pont de César est sur le Rhin", "César a institué un pont", "Le Rhin a un pont fait par César"], correct: 0 },
        { question: "Ut sementem feceris, ita metes.", options: ["Comme tu auras semé, ainsi tu récolteras", "La récolte dépend de la semence", "Il faut semer pour récolter", "La semence est comme la récolte"], correct: 0 },
        { question: "Timeo Danaos et dona ferentes (Virgile).", options: ["Je crains les Grecs, même quand ils apportent des cadeaux", "Je crains les Danaïdes et leurs cadeaux", "Les cadeaux des Grecs sont dangereux", "N'accepte jamais un cadeau d'un Grec"], correct: 0 },
    ],
    reconstitution: [
        { french: "Je pense, donc je suis", words: ["Cogito", "ergo", "sum"], correct: ["Cogito", "ergo", "sum"], declinaisons: ["nominatif"] },
        { french: "L'homme est un loup pour l'homme", words: ["Homo", "homini", "lupus", "est"], correct: ["Homo", "homini", "lupus", "est"], declinaisons: ["nominatif", "datif"] },
        { french: "L'erreur est humaine", words: ["Errare", "humanum", "est"], correct: ["Errare", "humanum", "est"], declinaisons: ["nominatif"] },
        { french: "Il faut obéir à la loi", words: ["Legi", "parendum", "est"], correct: ["Legi", "parendum", "est"], declinaisons: ["datif"] },
        { question: "La peur garde les vignes (et non le vigneron).", words: ["Timor", "custodit", "vineam"], correct: ["Timor", "custodit", "vineam"], declinaisons: ["nominatif", "accusatif"] },
        { question: "Il est difficile de supporter un malheur", words: ["Miserum", "est", "facinus", "ferre"], correct: ["Miserum", "est", "facinus", "ferre"], declinaisons: ["nominatif", "accusatif"] },
    ],
    vraifaux: [
        { latin: "Virtus", french: "Courage", correct: true },
        { latin: "Sapientia", french: "Science", correct: false },
        { latin: "Otium", french: "Loisir", correct: true },
        { latin: "Negotium", french: "Négligence", correct: false },
        { latin: "Foedus", french: "Traité", correct: true },
        { latin: "Coniuratio", french: "Complot", correct: true },
        { latin: "Auctoritas", french: "Auteur", correct: false },
        { latin: "Mos maiorum", french: "Les mœurs des anciens", correct: true },
    ],
    declinaison: [
        { question: "Quel cas est utilisé pour le complément d'objet direct (COD) ?", options: ["Nominatif", "Accusatif", "Génitif", "Datif"], correct: 1, declinaison: "1ere" },
        { question: "Le mot 'puella' est au nominatif. Mettez-le au datif pluriel.", options: ["puellas", "puellarum", "puellis", "puellae"], correct: 2, declinaison: "1ere" },
        { question: "Le mot 'ager, agri' (le champ) est à la 2ème déclinaison. Mettez 'ager bonus' au vocatif singulier.", options: ["ager bone", "agri boni", "ager bonus", "bone ager"], correct: 0, declinaison: "2eme" },
        { question: "Le mot 'donum' (le cadeau) est neutre. Quel est son accusatif pluriel ?", options: ["dona", "donos", "donorum", "donis"], correct: 0, declinaison: "2eme" },
        { question: "Le mot 'corpus, corporis' (le corps) est neutre. Quel est son nominatif pluriel ?", options: ["corpi", "corpora", "corpores", "corporum"], correct: 1, declinaison: "3eme" },
        { question: "Le mot 'mare, maris' (la mer) est un neutre de la 3ème déclinaison. Quel est son ablatif singulier ?", options: ["mare", "mari", "marum", "maribus"], correct: 1, declinaison: "3eme" },
        { question: "Le mot 'exercitus' (l'armée) est à la 4ème déclinaison. Quel est son génitif pluriel ?", options: ["exercitus", "exercituum", "exercitibus", "exercitui"], correct: 1, declinaison: "4eme" },
        { question: "Le mot 'cornu' (la corne) est neutre. Mettez-le à l'ablatif pluriel.", options: ["cornua", "cornibus", "cornuum", "cornu"], correct: 1, declinaison: "4eme" },
        { question: "Le mot 'spes, spei' (l'espoir) est à la 5ème déclinaison. Mettez-le à l'accusatif singulier.", options: ["spes", "spei", "spem", "spe"], correct: 2, declinaison: "5eme" },
        { question: "'rerum' est le génitif pluriel de 'res, rei' (la chose). Vrai ou Faux ?", options: ["Vrai", "Faux"], correct: 0, declinaison: "5eme" }
    ]
  }
};
